package view;
import dictionary.Dictionary;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author levi
 */
public class DictionaryWindow extends javax.swing.JFrame {
    private final JFileChooser openF;
    private Dictionary dictionary;
    private int action;//0 buscar palavra, 1 Semelhantes
    /**
     * Creates new form Home
     */
    public DictionaryWindow() {
        initComponents();
        openF = new JFileChooser();
        openF.setCurrentDirectory(new File("/home/levi"));
        dictionary = new Dictionary();
        this.number_panel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        status = new javax.swing.JPanel();
        btn_delete = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_insert = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_search = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_similar = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_print = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelStatus = new javax.swing.JLabel();
        number_panel = new javax.swing.JPanel();
        number_text = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        ordens = new javax.swing.JLabel();
        inputData = new javax.swing.JTextField();
        btn_ok = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(199, 199, 199));

        status.setBackground(new java.awt.Color(73, 73, 73));
        status.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_delete.setBackground(new java.awt.Color(64, 64, 64));
        btn_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_deleteMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_deleteMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_deleteMouseEntered(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 0, 21)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(209, 209, 209));
        jLabel3.setText("Excluir Palavras");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/delete2.png"))); // NOI18N

        javax.swing.GroupLayout btn_deleteLayout = new javax.swing.GroupLayout(btn_delete);
        btn_delete.setLayout(btn_deleteLayout);
        btn_deleteLayout.setHorizontalGroup(
            btn_deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_deleteLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        btn_deleteLayout.setVerticalGroup(
            btn_deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_deleteLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(btn_deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        status.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 280, 60));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dialog", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Dicionário");
        status.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        status.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 250, 2));

        btn_insert.setBackground(new java.awt.Color(64, 64, 64));
        btn_insert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_insertMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_insertMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_insertMouseEntered(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 0, 21)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(209, 209, 209));
        jLabel5.setText("Inserir Palavras");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/file2.png"))); // NOI18N

        javax.swing.GroupLayout btn_insertLayout = new javax.swing.GroupLayout(btn_insert);
        btn_insert.setLayout(btn_insertLayout);
        btn_insertLayout.setHorizontalGroup(
            btn_insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_insertLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        btn_insertLayout.setVerticalGroup(
            btn_insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_insertLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(17, 17, 17))
            .addGroup(btn_insertLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        status.add(btn_insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 280, 60));

        btn_search.setBackground(new java.awt.Color(64, 64, 64));
        btn_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_searchMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_searchMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_searchMouseEntered(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Dialog", 0, 21)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(209, 209, 209));
        jLabel7.setText("Buscar Palavra");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/search2.png"))); // NOI18N

        javax.swing.GroupLayout btn_searchLayout = new javax.swing.GroupLayout(btn_search);
        btn_search.setLayout(btn_searchLayout);
        btn_searchLayout.setHorizontalGroup(
            btn_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_searchLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        btn_searchLayout.setVerticalGroup(
            btn_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_searchLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(btn_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        status.add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 280, 60));

        btn_similar.setBackground(new java.awt.Color(64, 64, 64));
        btn_similar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_similarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_similarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_similarMouseEntered(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Dialog", 0, 21)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(209, 209, 209));
        jLabel9.setText("Semelhantes");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/equals2.png"))); // NOI18N

        javax.swing.GroupLayout btn_similarLayout = new javax.swing.GroupLayout(btn_similar);
        btn_similar.setLayout(btn_similarLayout);
        btn_similarLayout.setHorizontalGroup(
            btn_similarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_similarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_similarLayout.setVerticalGroup(
            btn_similarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_similarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(btn_similarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        status.add(btn_similar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 280, 60));

        btn_print.setBackground(new java.awt.Color(64, 64, 64));
        btn_print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_printMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_printMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_printMouseEntered(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Dialog", 0, 21)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(209, 209, 209));
        jLabel11.setText("Imprimir Dicionario");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/print2.png"))); // NOI18N

        javax.swing.GroupLayout btn_printLayout = new javax.swing.GroupLayout(btn_print);
        btn_print.setLayout(btn_printLayout);
        btn_printLayout.setHorizontalGroup(
            btn_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_printLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        btn_printLayout.setVerticalGroup(
            btn_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_printLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(btn_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        status.add(btn_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 280, 60));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Status");
        status.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 60, -1));

        labelStatus.setBackground(new java.awt.Color(204, 204, 204));
        labelStatus.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelStatus.setForeground(new java.awt.Color(204, 204, 204));
        labelStatus.setText("Iniciado");
        status.add(labelStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        number_panel.setBackground(new java.awt.Color(73, 73, 73));

        number_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number_textActionPerformed(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("Insira o Nº");

        javax.swing.GroupLayout number_panelLayout = new javax.swing.GroupLayout(number_panel);
        number_panel.setLayout(number_panelLayout);
        number_panelLayout.setHorizontalGroup(
            number_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(number_panelLayout.createSequentialGroup()
                .addGroup(number_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(number_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13))
                    .addComponent(number_text))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        number_panelLayout.setVerticalGroup(
            number_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, number_panelLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(number_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        status.add(number_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, 80));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(153, 153, 153));
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextArea1.setSelectionColor(new java.awt.Color(153, 153, 153));
        jScrollPane1.setViewportView(jTextArea1);

        ordens.setForeground(new java.awt.Color(153, 153, 153));
        ordens.setText("Input");

        inputData.setBackground(new java.awt.Color(255, 255, 255));
        inputData.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        inputData.setForeground(new java.awt.Color(153, 153, 153));
        inputData.setEnabled(false);
        inputData.setPreferredSize(new java.awt.Dimension(14, 25));
        inputData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDataActionPerformed(evt);
            }
        });
        inputData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputDataKeyPressed(evt);
            }
        });

        btn_ok.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/ok2.png"))); // NOI18N
        btn_ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_okMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_okMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_okMouseEntered(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/close2.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(inputData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(ordens)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel14))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE))
                .addContainerGap())
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(ordens)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputData, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_ok, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deleteMouseClicked
       
        
        this.btn_insert.setBackground(new java.awt.Color(64,64,64));
        this.btn_search.setBackground(new java.awt.Color(64,64,64));
        this.btn_similar.setBackground(new java.awt.Color(64,64,64));
        this.btn_print.setBackground(new java.awt.Color(64,64,64));
        
        this.inputData.setEnabled(false);
        this.btn_delete.setBackground(new java.awt.Color(119, 37, 192));
        int returnValue = this.openF.showOpenDialog(this);
        if(returnValue == JFileChooser.APPROVE_OPTION){
            this.dictionary.removeWords(openF.getSelectedFile().getAbsoluteFile().toString());
            this.jTextArea1.setText(this.dictionary.getWords());
            this.labelStatus.setText("Palavras Removidas");
        }
        this.btn_delete.setBackground(new java.awt.Color(64,64,64));
    }//GEN-LAST:event_btn_deleteMouseClicked

    private void btn_deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deleteMouseEntered
         this.btn_delete.setBackground(new java.awt.Color(86,86,86));
    }//GEN-LAST:event_btn_deleteMouseEntered

    private void btn_deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deleteMouseExited
        this.btn_delete.setBackground(new java.awt.Color(64,64,64));
        
    }//GEN-LAST:event_btn_deleteMouseExited

    private void btn_similarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_similarMouseEntered
        this.btn_similar.setBackground(new java.awt.Color(86,86,86));
    }//GEN-LAST:event_btn_similarMouseEntered

    private void btn_similarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_similarMouseExited
        this.btn_similar.setBackground(new java.awt.Color(64,64,64));
    }//GEN-LAST:event_btn_similarMouseExited

    private void btn_searchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseEntered
        this.btn_search.setBackground(new java.awt.Color(86,86,86));
    }//GEN-LAST:event_btn_searchMouseEntered

    private void btn_searchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseExited
        this.btn_search.setBackground(new java.awt.Color(64,64,64));
    }//GEN-LAST:event_btn_searchMouseExited

    private void btn_insertMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_insertMouseEntered
        this.btn_insert.setBackground(new java.awt.Color(86,86,86));
    }//GEN-LAST:event_btn_insertMouseEntered

    private void btn_insertMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_insertMouseExited
       this.btn_insert.setBackground(new java.awt.Color(64,64,64));
    }//GEN-LAST:event_btn_insertMouseExited

    private void btn_printMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_printMouseExited
       this.btn_print.setBackground(new java.awt.Color(64,64,64));
    }//GEN-LAST:event_btn_printMouseExited

    private void btn_printMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_printMouseEntered
        this.btn_print.setBackground(new java.awt.Color(86,86,86));
    }//GEN-LAST:event_btn_printMouseEntered

    private void btn_insertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_insertMouseClicked
        this.inputData.setEnabled(false);
        this.btn_insert.setBackground(new java.awt.Color(119, 37, 192));
        int returnValue = this.openF.showOpenDialog(this);
        if(returnValue == JFileChooser.APPROVE_OPTION){
            this.dictionary.insertWords(openF.getSelectedFile().getAbsoluteFile().toString());
            this.jTextArea1.setText(this.dictionary.getWords());
            this.labelStatus.setText("Arquivo Carregado");
        }
        this.btn_insert.setBackground(new java.awt.Color(64,64,64));
    }//GEN-LAST:event_btn_insertMouseClicked

    private void inputDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDataActionPerformed

    private void btn_okMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_okMouseEntered
       this.btn_ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/ok4.png")));
    }//GEN-LAST:event_btn_okMouseEntered

    private void btn_okMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_okMouseExited
       this.btn_ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/ok2.png")));
    }//GEN-LAST:event_btn_okMouseExited

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
        this.jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/close4.png")));
    }//GEN-LAST:event_jLabel14MouseEntered

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
        this.jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/close2.png")));
    }//GEN-LAST:event_jLabel14MouseExited

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void btn_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseClicked
        this.action = 0;
        this.btn_insert.setBackground(new java.awt.Color(64,64,64));
        this.btn_delete.setBackground(new java.awt.Color(64,64,64));
        this.btn_similar.setBackground(new java.awt.Color(64,64,64));
        this.btn_print.setBackground(new java.awt.Color(64,64,64));
        this.btn_search.setBackground(new java.awt.Color(119, 37, 192));
        
        this.inputData.setEnabled(true);
        this.labelStatus.setText("Insira a palavra para a busca");
        
    }//GEN-LAST:event_btn_searchMouseClicked

    private void btn_printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_printMouseClicked
        
        this.btn_insert.setBackground(new java.awt.Color(64,64,64));
        this.btn_search.setBackground(new java.awt.Color(64,64,64));
        this.btn_similar.setBackground(new java.awt.Color(64,64,64));
        this.btn_delete.setBackground(new java.awt.Color(64,64,64));
        
        this.btn_print.setBackground(new java.awt.Color(119, 37, 192));
        
        this.inputData.setEnabled(false);
        this.jTextArea1.setText(this.dictionary.getWords());
        this.labelStatus.setText("Dicionario Atual");
            
    }//GEN-LAST:event_btn_printMouseClicked

    private void btn_similarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_similarMouseClicked
        this.number_panel.setVisible(true);
        this.btn_insert.setBackground(new java.awt.Color(64,64,64));
        this.btn_search.setBackground(new java.awt.Color(64,64,64));
        this.btn_delete.setBackground(new java.awt.Color(64,64,64));
        this.btn_print.setBackground(new java.awt.Color(64,64,64));
        
        this.btn_similar.setBackground(new java.awt.Color(119, 37, 192));
        
        this.inputData.setEnabled(true);
        this.labelStatus.setText("Insira a palavra");
        this.action = 1;
    }//GEN-LAST:event_btn_similarMouseClicked

    private void btn_okMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_okMouseClicked
        String aux = "";
        if(this.action == 0 && this.inputData.isEnabled()) {
            aux = this.dictionary.queryWord(this.inputData.getText());
            this.jTextArea1.setText(aux);
        }else if(this.action == 1 && this.inputData.isEnabled()){
            aux = this.dictionary.similar(this.inputData.getText(), Integer.parseInt(this.number_text.getText()));
            this.jTextArea1.setText(aux);
            this.number_panel.setVisible(false);
        }
    }//GEN-LAST:event_btn_okMouseClicked

    private void number_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_number_textActionPerformed

    private void inputDataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputDataKeyPressed
        String aux = "";
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            if(this.action == 0 && this.inputData.isEnabled()) {
                aux = this.dictionary.queryWord(this.inputData.getText());
                this.jTextArea1.setText(aux);
            }else if(this.action == 1 && this.inputData.isEnabled()){
                aux = this.dictionary.similar(this.inputData.getText(), Integer.parseInt(this.number_text.getText()));
                this.jTextArea1.setText(aux);
                this.number_panel.setVisible(false);
        }
        }
    }//GEN-LAST:event_inputDataKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DictionaryWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DictionaryWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DictionaryWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DictionaryWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DictionaryWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btn_delete;
    private javax.swing.JPanel btn_insert;
    private javax.swing.JLabel btn_ok;
    private javax.swing.JPanel btn_print;
    private javax.swing.JPanel btn_search;
    private javax.swing.JPanel btn_similar;
    private javax.swing.JTextField inputData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JPanel number_panel;
    private javax.swing.JTextField number_text;
    private javax.swing.JLabel ordens;
    private javax.swing.JPanel status;
    // End of variables declaration//GEN-END:variables
}
